sudo: false

language: rust

cache: cargo

rust:
  - stable

os:
  - linux
  - osx

script:
  - cargo build --verbose --all
  - cargo test --verbose --all

notifications:
  email:
    recipients:
      - cassio@kirch7.com
    on_success: always
